version: "3.9"
services:
  vox-populi-tool-dashboard:
    image: "docker-hub.mobi-phupgniezno.pl/phup.vox-populi-tool-dashboard:latest"
    restart: always
    environment:
      - TZ=Europe/Warsaw
    networks:
      - traefik-net
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.test-vox-populi-tool-dashboard.rule=Host(`test-vox.mobi-phupgniezno.pl`)"
        - "traefik.http.routers.test-vox-populi-tool-dashboard.entrypoints=https"
        - "traefik.http.routers.test-vox-populi-tool-dashboard.service=test-vox-populi-tool-dashboard-service"
        - "traefik.http.routers.test-vox-populi-tool-dashboard.tls=true"
        - "traefik.http.services.test-vox-populi-tool-dashboard-service.loadbalancer.server.port=8080"


networks:
  traefik-net:
    external: true